// Generated by gencpp from file thesis_aurian/refdoors.msg
// DO NOT EDIT!


#ifndef THESIS_AURIAN_MESSAGE_REFDOORS_H
#define THESIS_AURIAN_MESSAGE_REFDOORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace thesis_aurian
{
template <class ContainerAllocator>
struct refdoors_
{
  typedef refdoors_<ContainerAllocator> Type;

  refdoors_()
    : data()  {
    }
  refdoors_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::thesis_aurian::refdoors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::thesis_aurian::refdoors_<ContainerAllocator> const> ConstPtr;

}; // struct refdoors_

typedef ::thesis_aurian::refdoors_<std::allocator<void> > refdoors;

typedef boost::shared_ptr< ::thesis_aurian::refdoors > refdoorsPtr;
typedef boost::shared_ptr< ::thesis_aurian::refdoors const> refdoorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::thesis_aurian::refdoors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::thesis_aurian::refdoors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace thesis_aurian

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ardrone_autonomy': ['/opt/ros/indigo/share/ardrone_autonomy/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'thesis_aurian': ['/home/laboinmastudent/Bureau/Drone_thesis_2017/Code/src/thesis_aurian/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::thesis_aurian::refdoors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thesis_aurian::refdoors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thesis_aurian::refdoors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thesis_aurian::refdoors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thesis_aurian::refdoors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thesis_aurian::refdoors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::thesis_aurian::refdoors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f43a8e1b362b75baa741461b46adc7e0";
  }

  static const char* value(const ::thesis_aurian::refdoors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf43a8e1b362b75baULL;
  static const uint64_t static_value2 = 0xa741461b46adc7e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::thesis_aurian::refdoors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "thesis_aurian/refdoors";
  }

  static const char* value(const ::thesis_aurian::refdoors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::thesis_aurian::refdoors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This contains all the reference doors and open spaces for the matching step.\n\
\n\
uint8[] data\n\
";
  }

  static const char* value(const ::thesis_aurian::refdoors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::thesis_aurian::refdoors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct refdoors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::thesis_aurian::refdoors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::thesis_aurian::refdoors_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // THESIS_AURIAN_MESSAGE_REFDOORS_H
